---
docs_dir: docs
edit_uri: edit/master/docs
repo_url: https://github.com/sblack4/18-s097-applied-category-theory-january-iap-2019
site_description: Course notes for 18.S097 Applied Category Theory
site_name: 18-s097-applied-category-theory-january-iap-2019

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex
  - smarty
  - toc
  # - sane_lists
  # - def_list
  # - mdx_gh_links:
  #     user: sblack4
  #     repo: 18-s097-applied-category-theory-january-iap-2019
# nav:
#   - Home: index.md
#   - 'Issue Tracker': 'https://github.com/sblack4/18-s097-applied-category-theory-january-iap-2019/issues'
#   - Chapters: '/chapters/'

plugins:
  - search

theme:
  name: 'material'
  feature:
    tabs: true
  palette:
        primary: 'black'
        accent: 'deep-orange'

