---
docs_dir: docs
edit_uri: edit/master/docs
repo_url: https://github.com/sblack4/18-s097-applied-category-theory-january-iap-2019
site_description: Course notes for 18.S097 Applied Category Theory
site_name: 18-s097-applied-category-theory-january-iap-2019

markdown_extensions:
    - toc

nav:
  - home: 'README.md'

plugins:
  - search
  
theme:
  name: 'material'
  palette:
        primary: 'black'
        accent: 'deep-orange'
  feature:
    tabs: true
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - toc
    - admonition
    - pymdownx.arithmatex
#     - markdown_include.include:
#         base_path: docs
